# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 218537e918e666ff231eb2f24284a48a210ec18d98adbee4586f25c841fb9e33c940942ce93ff11d2cc57e5fca928d91a545e1b7474d0278b49b69e7c36d4c74

test:
  secret_key_base: 5adf5d4bc6e62fbaa6e7d05ff598884ee201dbbe844495f080f1be3447e6a34669cea6b94f194dd3f7658751c95e2cb85a15cef9801b10305bacbad4794dc799

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
